# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65vents.proto\x12\x06\x65vents\"!\n\x05Topic\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"7\n\x05\x45vent\x12\x1d\n\x06topics\x18\x01 \x03(\x0b\x32\r.events.Topic\x12\x0f\n\x07message\x18\x02 \x01(\t2f\n\x06\x45vents\x12-\n\tsubscribe\x12\r.events.Topic\x1a\r.events.Event\"\x00\x30\x01\x12-\n\x0bunsubscribe\x12\r.events.Topic\x1a\r.events.Topic\"\x00\x42\n\n\x06\x65ventsP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'events_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\006eventsP\001'
  _TOPIC._serialized_start=24
  _TOPIC._serialized_end=57
  _EVENT._serialized_start=59
  _EVENT._serialized_end=114
  _EVENTS._serialized_start=116
  _EVENTS._serialized_end=218
# @@protoc_insertion_point(module_scope)
