# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import events_pb2 as events__pb2


class EventsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.subscribe = channel.unary_stream(
                '/events.Events/subscribe',
                request_serializer=events__pb2.Topic.SerializeToString,
                response_deserializer=events__pb2.Event.FromString,
                )
        self.unsubscribe = channel.unary_unary(
                '/events.Events/unsubscribe',
                request_serializer=events__pb2.Topic.SerializeToString,
                response_deserializer=events__pb2.Topic.FromString,
                )


class EventsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def unsubscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.subscribe,
                    request_deserializer=events__pb2.Topic.FromString,
                    response_serializer=events__pb2.Event.SerializeToString,
            ),
            'unsubscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.unsubscribe,
                    request_deserializer=events__pb2.Topic.FromString,
                    response_serializer=events__pb2.Topic.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'events.Events', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Events(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/events.Events/subscribe',
            events__pb2.Topic.SerializeToString,
            events__pb2.Event.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def unsubscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/events.Events/unsubscribe',
            events__pb2.Topic.SerializeToString,
            events__pb2.Topic.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
